
# This file is automatically generated, you probably don't want to edit this

eduChiSquareGoodnessOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "eduChiSquareGoodnessOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            variable = NULL,
            counts = NULL,
            expectedRatios = "",
            reportStyle = "apa7",
            reportFormat = "paragraph",
            reportTone = "student_friendly",
            reportDescriptives = TRUE,
            reportAssumptions = TRUE,
            reportStatistic = TRUE,
            reportDf = TRUE,
            reportP = TRUE,
            reportEffect = TRUE,
            reportCI = TRUE,
            reportInterpretation = TRUE,
            reportCautions = TRUE, ...) {

            super$initialize(
                package="JamoviReport",
                name="eduChiSquareGoodness",
                requiresData=TRUE,
                ...)

            private$..variable <- jmvcore::OptionVariable$new(
                "variable",
                variable,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..counts <- jmvcore::OptionVariable$new(
                "counts",
                counts,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..expectedRatios <- jmvcore::OptionString$new(
                "expectedRatios",
                expectedRatios,
                default="")
            private$..reportStyle <- jmvcore::OptionList$new(
                "reportStyle",
                reportStyle,
                options=list(
                    "apa7",
                    "plain",
                    "journal",
                    "dissertation"),
                default="apa7")
            private$..reportFormat <- jmvcore::OptionList$new(
                "reportFormat",
                reportFormat,
                options=list(
                    "short",
                    "paragraph",
                    "bullets",
                    "table_paragraph",
                    "copy_ready"),
                default="paragraph")
            private$..reportTone <- jmvcore::OptionList$new(
                "reportTone",
                reportTone,
                options=list(
                    "concise",
                    "student_friendly",
                    "detailed",
                    "critical"),
                default="student_friendly")
            private$..reportDescriptives <- jmvcore::OptionBool$new(
                "reportDescriptives",
                reportDescriptives,
                default=TRUE)
            private$..reportAssumptions <- jmvcore::OptionBool$new(
                "reportAssumptions",
                reportAssumptions,
                default=TRUE)
            private$..reportStatistic <- jmvcore::OptionBool$new(
                "reportStatistic",
                reportStatistic,
                default=TRUE)
            private$..reportDf <- jmvcore::OptionBool$new(
                "reportDf",
                reportDf,
                default=TRUE)
            private$..reportP <- jmvcore::OptionBool$new(
                "reportP",
                reportP,
                default=TRUE)
            private$..reportEffect <- jmvcore::OptionBool$new(
                "reportEffect",
                reportEffect,
                default=TRUE)
            private$..reportCI <- jmvcore::OptionBool$new(
                "reportCI",
                reportCI,
                default=TRUE)
            private$..reportInterpretation <- jmvcore::OptionBool$new(
                "reportInterpretation",
                reportInterpretation,
                default=TRUE)
            private$..reportCautions <- jmvcore::OptionBool$new(
                "reportCautions",
                reportCautions,
                default=TRUE)

            self$.addOption(private$..variable)
            self$.addOption(private$..counts)
            self$.addOption(private$..expectedRatios)
            self$.addOption(private$..reportStyle)
            self$.addOption(private$..reportFormat)
            self$.addOption(private$..reportTone)
            self$.addOption(private$..reportDescriptives)
            self$.addOption(private$..reportAssumptions)
            self$.addOption(private$..reportStatistic)
            self$.addOption(private$..reportDf)
            self$.addOption(private$..reportP)
            self$.addOption(private$..reportEffect)
            self$.addOption(private$..reportCI)
            self$.addOption(private$..reportInterpretation)
            self$.addOption(private$..reportCautions)
        }),
    active = list(
        variable = function() private$..variable$value,
        counts = function() private$..counts$value,
        expectedRatios = function() private$..expectedRatios$value,
        reportStyle = function() private$..reportStyle$value,
        reportFormat = function() private$..reportFormat$value,
        reportTone = function() private$..reportTone$value,
        reportDescriptives = function() private$..reportDescriptives$value,
        reportAssumptions = function() private$..reportAssumptions$value,
        reportStatistic = function() private$..reportStatistic$value,
        reportDf = function() private$..reportDf$value,
        reportP = function() private$..reportP$value,
        reportEffect = function() private$..reportEffect$value,
        reportCI = function() private$..reportCI$value,
        reportInterpretation = function() private$..reportInterpretation$value,
        reportCautions = function() private$..reportCautions$value),
    private = list(
        ..variable = NA,
        ..counts = NA,
        ..expectedRatios = NA,
        ..reportStyle = NA,
        ..reportFormat = NA,
        ..reportTone = NA,
        ..reportDescriptives = NA,
        ..reportAssumptions = NA,
        ..reportStatistic = NA,
        ..reportDf = NA,
        ..reportP = NA,
        ..reportEffect = NA,
        ..reportCI = NA,
        ..reportInterpretation = NA,
        ..reportCautions = NA)
)

eduChiSquareGoodnessResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "eduChiSquareGoodnessResults",
    inherit = jmvcore::Group,
    active = list(
        overview = function() private$.items[["overview"]],
        fit = function() private$.items[["fit"]],
        cells = function() private$.items[["cells"]],
        diagnostics = function() private$.items[["diagnostics"]],
        report = function() private$.items[["report"]],
        interpretation = function() private$.items[["interpretation"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Guided Chi-Square Goodness-of-Fit")
            self$add(jmvcore::Html$new(
                options=options,
                name="overview",
                title="JamoviReport: Overview and Why This Test?"))
            self$add(jmvcore::Table$new(
                options=options,
                name="fit",
                title="Main Results and Effect Size",
                columns=list(
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Chi-square", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="effect", 
                        `title`="Cohen's w", 
                        `type`="number"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="cells",
                title="Observed, Expected, and Standardised Residual Counts",
                columns=list(
                    list(
                        `name`="category", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="observed", 
                        `title`="Observed", 
                        `type`="number"),
                    list(
                        `name`="expected", 
                        `title`="Expected", 
                        `type`="number"),
                    list(
                        `name`="standardised_residual", 
                        `title`="Standardised Residual", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="diagnostics",
                title="Assumption Checks and Guidance",
                columns=list(
                    list(
                        `name`="check", 
                        `title`="Check", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="status", 
                        `title`="Status", 
                        `type`="text"),
                    list(
                        `name`="interpretation", 
                        `title`="Interpretation", 
                        `type`="text"),
                    list(
                        `name`="action", 
                        `title`="Recommended Action", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="report",
                title="Reporting"))
            self$add(jmvcore::Html$new(
                options=options,
                name="interpretation",
                title="Plain-Language Interpretation"))}))

eduChiSquareGoodnessBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "eduChiSquareGoodnessBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "JamoviReport",
                name = "eduChiSquareGoodness",
                version = c(0,1,0),
                options = options,
                results = eduChiSquareGoodnessResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Guided Chi-Square Goodness-of-Fit
#'
#' Compare observed categorical frequencies with an expected distribution, 
#' with assumption guidance and report-ready explanation.
#' 
#' @param data .
#' @param variable .
#' @param counts .
#' @param expectedRatios .
#' @param reportStyle .
#' @param reportFormat .
#' @param reportTone .
#' @param reportDescriptives .
#' @param reportAssumptions .
#' @param reportStatistic .
#' @param reportDf .
#' @param reportP .
#' @param reportEffect .
#' @param reportCI .
#' @param reportInterpretation .
#' @param reportCautions .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$overview} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$fit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$cells} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$diagnostics} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$report} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$interpretation} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$fit$asDF}
#'
#' \code{as.data.frame(results$fit)}
#'
#' @export
eduChiSquareGoodness <- function(
    data,
    variable,
    counts = NULL,
    expectedRatios = "",
    reportStyle = "apa7",
    reportFormat = "paragraph",
    reportTone = "student_friendly",
    reportDescriptives = TRUE,
    reportAssumptions = TRUE,
    reportStatistic = TRUE,
    reportDf = TRUE,
    reportP = TRUE,
    reportEffect = TRUE,
    reportCI = TRUE,
    reportInterpretation = TRUE,
    reportCautions = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("eduChiSquareGoodness requires jmvcore to be installed (restart may be required)")

    if ( ! missing(variable)) variable <- jmvcore::resolveQuo(jmvcore::enquo(variable))
    if ( ! missing(counts)) counts <- jmvcore::resolveQuo(jmvcore::enquo(counts))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(variable), variable, NULL),
            `if`( ! missing(counts), counts, NULL))

    for (v in variable) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- eduChiSquareGoodnessOptions$new(
        variable = variable,
        counts = counts,
        expectedRatios = expectedRatios,
        reportStyle = reportStyle,
        reportFormat = reportFormat,
        reportTone = reportTone,
        reportDescriptives = reportDescriptives,
        reportAssumptions = reportAssumptions,
        reportStatistic = reportStatistic,
        reportDf = reportDf,
        reportP = reportP,
        reportEffect = reportEffect,
        reportCI = reportCI,
        reportInterpretation = reportInterpretation,
        reportCautions = reportCautions)

    analysis <- eduChiSquareGoodnessClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

