
# This file is automatically generated, you probably don't want to edit this

eduCorrelationOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "eduCorrelationOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            x = NULL,
            y = NULL,
            method = "pearson",
            ciWidth = 95,
            showPlot = TRUE,
            reportStyle = "apa7",
            reportFormat = "paragraph",
            reportTone = "student_friendly",
            reportDescriptives = TRUE,
            reportAssumptions = TRUE,
            reportStatistic = TRUE,
            reportDf = TRUE,
            reportP = TRUE,
            reportEffect = TRUE,
            reportCI = TRUE,
            reportInterpretation = TRUE,
            reportCautions = TRUE, ...) {

            super$initialize(
                package="jReport",
                name="eduCorrelation",
                requiresData=TRUE,
                ...)

            private$..x <- jmvcore::OptionVariable$new(
                "x",
                x,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..y <- jmvcore::OptionVariable$new(
                "y",
                y,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "pearson",
                    "spearman",
                    "kendall"),
                default="pearson")
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..showPlot <- jmvcore::OptionBool$new(
                "showPlot",
                showPlot,
                default=TRUE)
            private$..reportStyle <- jmvcore::OptionList$new(
                "reportStyle",
                reportStyle,
                options=list(
                    "apa7",
                    "plain",
                    "journal",
                    "dissertation"),
                default="apa7")
            private$..reportFormat <- jmvcore::OptionList$new(
                "reportFormat",
                reportFormat,
                options=list(
                    "short",
                    "paragraph",
                    "bullets",
                    "table_paragraph",
                    "copy_ready"),
                default="paragraph")
            private$..reportTone <- jmvcore::OptionList$new(
                "reportTone",
                reportTone,
                options=list(
                    "concise",
                    "student_friendly",
                    "detailed",
                    "critical"),
                default="student_friendly")
            private$..reportDescriptives <- jmvcore::OptionBool$new(
                "reportDescriptives",
                reportDescriptives,
                default=TRUE)
            private$..reportAssumptions <- jmvcore::OptionBool$new(
                "reportAssumptions",
                reportAssumptions,
                default=TRUE)
            private$..reportStatistic <- jmvcore::OptionBool$new(
                "reportStatistic",
                reportStatistic,
                default=TRUE)
            private$..reportDf <- jmvcore::OptionBool$new(
                "reportDf",
                reportDf,
                default=TRUE)
            private$..reportP <- jmvcore::OptionBool$new(
                "reportP",
                reportP,
                default=TRUE)
            private$..reportEffect <- jmvcore::OptionBool$new(
                "reportEffect",
                reportEffect,
                default=TRUE)
            private$..reportCI <- jmvcore::OptionBool$new(
                "reportCI",
                reportCI,
                default=TRUE)
            private$..reportInterpretation <- jmvcore::OptionBool$new(
                "reportInterpretation",
                reportInterpretation,
                default=TRUE)
            private$..reportCautions <- jmvcore::OptionBool$new(
                "reportCautions",
                reportCautions,
                default=TRUE)

            self$.addOption(private$..x)
            self$.addOption(private$..y)
            self$.addOption(private$..method)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..showPlot)
            self$.addOption(private$..reportStyle)
            self$.addOption(private$..reportFormat)
            self$.addOption(private$..reportTone)
            self$.addOption(private$..reportDescriptives)
            self$.addOption(private$..reportAssumptions)
            self$.addOption(private$..reportStatistic)
            self$.addOption(private$..reportDf)
            self$.addOption(private$..reportP)
            self$.addOption(private$..reportEffect)
            self$.addOption(private$..reportCI)
            self$.addOption(private$..reportInterpretation)
            self$.addOption(private$..reportCautions)
        }),
    active = list(
        x = function() private$..x$value,
        y = function() private$..y$value,
        method = function() private$..method$value,
        ciWidth = function() private$..ciWidth$value,
        showPlot = function() private$..showPlot$value,
        reportStyle = function() private$..reportStyle$value,
        reportFormat = function() private$..reportFormat$value,
        reportTone = function() private$..reportTone$value,
        reportDescriptives = function() private$..reportDescriptives$value,
        reportAssumptions = function() private$..reportAssumptions$value,
        reportStatistic = function() private$..reportStatistic$value,
        reportDf = function() private$..reportDf$value,
        reportP = function() private$..reportP$value,
        reportEffect = function() private$..reportEffect$value,
        reportCI = function() private$..reportCI$value,
        reportInterpretation = function() private$..reportInterpretation$value,
        reportCautions = function() private$..reportCautions$value),
    private = list(
        ..x = NA,
        ..y = NA,
        ..method = NA,
        ..ciWidth = NA,
        ..showPlot = NA,
        ..reportStyle = NA,
        ..reportFormat = NA,
        ..reportTone = NA,
        ..reportDescriptives = NA,
        ..reportAssumptions = NA,
        ..reportStatistic = NA,
        ..reportDf = NA,
        ..reportP = NA,
        ..reportEffect = NA,
        ..reportCI = NA,
        ..reportInterpretation = NA,
        ..reportCautions = NA)
)

eduCorrelationResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "eduCorrelationResults",
    inherit = jmvcore::Group,
    active = list(
        overview = function() private$.items[["overview"]],
        main = function() private$.items[["main"]],
        descriptives = function() private$.items[["descriptives"]],
        diagnostics = function() private$.items[["diagnostics"]],
        report = function() private$.items[["report"]],
        interpretation = function() private$.items[["interpretation"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Guided Correlation",
                refs=list(
                    "jReport",
                    "effectsize",
                    "ggplot2",
                    "Cohen1988",
                    "Cumming2014"))
            self$add(jmvcore::Html$new(
                options=options,
                name="overview",
                title="jReport: Overview and Why This Test?",
                refs=list(
                    "jReport",
                    "effectsize",
                    "ggplot2",
                    "Cohen1988",
                    "Cumming2014")))
            self$add(jmvcore::Table$new(
                options=options,
                name="main",
                title="Main Result",
                clearWith=list(
                    "x",
                    "yes",
                    "method",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="test", 
                        `title`="Method", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Coefficient", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="ci_low", 
                        `title`="CI Lower", 
                        `type`="number"),
                    list(
                        `name`="ci_high", 
                        `title`="CI Upper", 
                        `type`="number")),
                refs=list(
                    "jReport",
                    "effectsize",
                    "ggplot2",
                    "Cohen1988",
                    "Cumming2014")))
            self$add(jmvcore::Table$new(
                options=options,
                name="descriptives",
                title="Descriptive Statistics",
                clearWith=list(
                    "x",
                    "yes",
                    "method",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="label", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number")),
                refs=list(
                    "jReport",
                    "effectsize",
                    "ggplot2",
                    "Cohen1988",
                    "Cumming2014")))
            self$add(jmvcore::Table$new(
                options=options,
                name="diagnostics",
                title="Assumption Checks and Guidance",
                clearWith=list(
                    "x",
                    "yes",
                    "method",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="check", 
                        `title`="Check", 
                        `type`="text"),
                    list(
                        `name`="tested", 
                        `title`="Tested?", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="status", 
                        `title`="Status", 
                        `type`="text"),
                    list(
                        `name`="interpretation", 
                        `title`="Interpretation", 
                        `type`="text"),
                    list(
                        `name`="action", 
                        `title`="Recommended Action", 
                        `type`="text")),
                refs=list(
                    "jReport",
                    "effectsize",
                    "ggplot2",
                    "Cohen1988",
                    "Cumming2014")))
            self$add(jmvcore::Html$new(
                options=options,
                name="report",
                title="Reporting",
                refs=list(
                    "jReport",
                    "effectsize",
                    "ggplot2",
                    "Cohen1988",
                    "Cumming2014")))
            self$add(jmvcore::Html$new(
                options=options,
                name="interpretation",
                title="Plain-Language Interpretation",
                refs=list(
                    "jReport",
                    "effectsize",
                    "ggplot2",
                    "Cohen1988",
                    "Cumming2014")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Visualisation",
                visible="(showPlot)",
                clearWith=list(
                    "x",
                    "yes",
                    "method",
                    "ciWidth"),
                width=520,
                height=360,
                renderFun=".plot",
                refs=list(
                    "jReport",
                    "effectsize",
                    "ggplot2",
                    "Cohen1988",
                    "Cumming2014")))}))

eduCorrelationBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "eduCorrelationBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReport",
                name = "eduCorrelation",
                version = c(1,0,0),
                options = options,
                results = eduCorrelationResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Guided Correlation
#'
#' Explain the direction, strength, assumptions, and reporting of an 
#' association between two numeric variables.
#' 
#' @section References:
#' jReport
#'
#' effectsize
#'
#' ggplot2
#'
#' @param data .
#' @param x .
#' @param y .
#' @param method .
#' @param ciWidth .
#' @param showPlot .
#' @param reportStyle .
#' @param reportFormat .
#' @param reportTone .
#' @param reportDescriptives .
#' @param reportAssumptions .
#' @param reportStatistic .
#' @param reportDf .
#' @param reportP .
#' @param reportEffect .
#' @param reportCI .
#' @param reportInterpretation .
#' @param reportCautions .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$overview} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$main} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$descriptives} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$diagnostics} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$report} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$interpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$main$asDF}
#'
#' \code{as.data.frame(results$main)}
#'
#' @export
eduCorrelation <- function(
    data,
    x,
    y,
    method = "pearson",
    ciWidth = 95,
    showPlot = TRUE,
    reportStyle = "apa7",
    reportFormat = "paragraph",
    reportTone = "student_friendly",
    reportDescriptives = TRUE,
    reportAssumptions = TRUE,
    reportStatistic = TRUE,
    reportDf = TRUE,
    reportP = TRUE,
    reportEffect = TRUE,
    reportCI = TRUE,
    reportInterpretation = TRUE,
    reportCautions = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("eduCorrelation requires jmvcore to be installed (restart may be required)")

    if ( ! missing(x)) x <- jmvcore::resolveQuo(jmvcore::enquo(x))
    if ( ! missing(y)) y <- jmvcore::resolveQuo(jmvcore::enquo(y))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(x), x, NULL),
            `if`( ! missing(y), y, NULL))


    options <- eduCorrelationOptions$new(
        x = x,
        y = y,
        method = method,
        ciWidth = ciWidth,
        showPlot = showPlot,
        reportStyle = reportStyle,
        reportFormat = reportFormat,
        reportTone = reportTone,
        reportDescriptives = reportDescriptives,
        reportAssumptions = reportAssumptions,
        reportStatistic = reportStatistic,
        reportDf = reportDf,
        reportP = reportP,
        reportEffect = reportEffect,
        reportCI = reportCI,
        reportInterpretation = reportInterpretation,
        reportCautions = reportCautions)

    analysis <- eduCorrelationClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

