
# This file is automatically generated, you probably don't want to edit this

eduLogisticOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "eduLogisticOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            outcome = NULL,
            covariates = NULL,
            factors = NULL,
            ciWidth = 95,
            reportStyle = "apa7",
            reportFormat = "paragraph",
            reportTone = "student_friendly",
            reportDescriptives = TRUE,
            reportAssumptions = TRUE,
            reportStatistic = TRUE,
            reportDf = TRUE,
            reportP = TRUE,
            reportEffect = TRUE,
            reportCI = TRUE,
            reportInterpretation = TRUE,
            reportCautions = TRUE, ...) {

            super$initialize(
                package="jReport",
                name="eduLogistic",
                requiresData=TRUE,
                ...)

            private$..outcome <- jmvcore::OptionVariable$new(
                "outcome",
                outcome,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"),
                default=NULL)
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"),
                default=NULL)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..reportStyle <- jmvcore::OptionList$new(
                "reportStyle",
                reportStyle,
                options=list(
                    "apa7",
                    "plain",
                    "journal",
                    "dissertation"),
                default="apa7")
            private$..reportFormat <- jmvcore::OptionList$new(
                "reportFormat",
                reportFormat,
                options=list(
                    "short",
                    "paragraph",
                    "bullets",
                    "table_paragraph",
                    "copy_ready"),
                default="paragraph")
            private$..reportTone <- jmvcore::OptionList$new(
                "reportTone",
                reportTone,
                options=list(
                    "concise",
                    "student_friendly",
                    "detailed",
                    "critical"),
                default="student_friendly")
            private$..reportDescriptives <- jmvcore::OptionBool$new(
                "reportDescriptives",
                reportDescriptives,
                default=TRUE)
            private$..reportAssumptions <- jmvcore::OptionBool$new(
                "reportAssumptions",
                reportAssumptions,
                default=TRUE)
            private$..reportStatistic <- jmvcore::OptionBool$new(
                "reportStatistic",
                reportStatistic,
                default=TRUE)
            private$..reportDf <- jmvcore::OptionBool$new(
                "reportDf",
                reportDf,
                default=TRUE)
            private$..reportP <- jmvcore::OptionBool$new(
                "reportP",
                reportP,
                default=TRUE)
            private$..reportEffect <- jmvcore::OptionBool$new(
                "reportEffect",
                reportEffect,
                default=TRUE)
            private$..reportCI <- jmvcore::OptionBool$new(
                "reportCI",
                reportCI,
                default=TRUE)
            private$..reportInterpretation <- jmvcore::OptionBool$new(
                "reportInterpretation",
                reportInterpretation,
                default=TRUE)
            private$..reportCautions <- jmvcore::OptionBool$new(
                "reportCautions",
                reportCautions,
                default=TRUE)

            self$.addOption(private$..outcome)
            self$.addOption(private$..covariates)
            self$.addOption(private$..factors)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..reportStyle)
            self$.addOption(private$..reportFormat)
            self$.addOption(private$..reportTone)
            self$.addOption(private$..reportDescriptives)
            self$.addOption(private$..reportAssumptions)
            self$.addOption(private$..reportStatistic)
            self$.addOption(private$..reportDf)
            self$.addOption(private$..reportP)
            self$.addOption(private$..reportEffect)
            self$.addOption(private$..reportCI)
            self$.addOption(private$..reportInterpretation)
            self$.addOption(private$..reportCautions)
        }),
    active = list(
        outcome = function() private$..outcome$value,
        covariates = function() private$..covariates$value,
        factors = function() private$..factors$value,
        ciWidth = function() private$..ciWidth$value,
        reportStyle = function() private$..reportStyle$value,
        reportFormat = function() private$..reportFormat$value,
        reportTone = function() private$..reportTone$value,
        reportDescriptives = function() private$..reportDescriptives$value,
        reportAssumptions = function() private$..reportAssumptions$value,
        reportStatistic = function() private$..reportStatistic$value,
        reportDf = function() private$..reportDf$value,
        reportP = function() private$..reportP$value,
        reportEffect = function() private$..reportEffect$value,
        reportCI = function() private$..reportCI$value,
        reportInterpretation = function() private$..reportInterpretation$value,
        reportCautions = function() private$..reportCautions$value),
    private = list(
        ..outcome = NA,
        ..covariates = NA,
        ..factors = NA,
        ..ciWidth = NA,
        ..reportStyle = NA,
        ..reportFormat = NA,
        ..reportTone = NA,
        ..reportDescriptives = NA,
        ..reportAssumptions = NA,
        ..reportStatistic = NA,
        ..reportDf = NA,
        ..reportP = NA,
        ..reportEffect = NA,
        ..reportCI = NA,
        ..reportInterpretation = NA,
        ..reportCautions = NA)
)

eduLogisticResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "eduLogisticResults",
    inherit = jmvcore::Group,
    active = list(
        overview = function() private$.items[["overview"]],
        fit = function() private$.items[["fit"]],
        coefficients = function() private$.items[["coefficients"]],
        diagnostics = function() private$.items[["diagnostics"]],
        report = function() private$.items[["report"]],
        interpretation = function() private$.items[["interpretation"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Guided Binomial Logistic Regression",
                refs=list(
                    "jReport",
                    "parameters",
                    "performance",
                    "effectsize"))
            self$add(jmvcore::Html$new(
                options=options,
                name="overview",
                title="jReport: Overview and Why This Test?",
                refs=list(
                    "jReport",
                    "parameters",
                    "performance",
                    "effectsize")))
            self$add(jmvcore::Table$new(
                options=options,
                name="fit",
                title="Main Results and Model Fit",
                clearWith=list(
                    "outcome",
                    "covariates",
                    "factors",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Chi-square", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="r2", 
                        `title`="McFadden R-squared", 
                        `type`="number")),
                refs=list(
                    "jReport",
                    "parameters",
                    "performance",
                    "effectsize")))
            self$add(jmvcore::Table$new(
                options=options,
                name="coefficients",
                title="Coefficients and Odds Ratios",
                clearWith=list(
                    "outcome",
                    "covariates",
                    "factors",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="term", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="B", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="z", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="odds_ratio", 
                        `title`="Odds Ratio", 
                        `type`="number"),
                    list(
                        `name`="lower", 
                        `title`="OR CI Lower", 
                        `type`="number"),
                    list(
                        `name`="upper", 
                        `title`="OR CI Upper", 
                        `type`="number")),
                refs=list(
                    "jReport",
                    "parameters",
                    "performance",
                    "effectsize")))
            self$add(jmvcore::Table$new(
                options=options,
                name="diagnostics",
                title="Diagnostic Checks and Guidance",
                clearWith=list(
                    "outcome",
                    "covariates",
                    "factors",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="check", 
                        `title`="Check", 
                        `type`="text"),
                    list(
                        `name`="tested", 
                        `title`="Tested?", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="status", 
                        `title`="Status", 
                        `type`="text"),
                    list(
                        `name`="interpretation", 
                        `title`="Interpretation", 
                        `type`="text"),
                    list(
                        `name`="action", 
                        `title`="Recommended Action", 
                        `type`="text")),
                refs=list(
                    "jReport",
                    "parameters",
                    "performance",
                    "effectsize")))
            self$add(jmvcore::Html$new(
                options=options,
                name="report",
                title="Reporting",
                refs=list(
                    "jReport",
                    "parameters",
                    "performance",
                    "effectsize")))
            self$add(jmvcore::Html$new(
                options=options,
                name="interpretation",
                title="Plain-Language Interpretation",
                refs=list(
                    "jReport",
                    "parameters",
                    "performance",
                    "effectsize")))}))

eduLogisticBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "eduLogisticBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReport",
                name = "eduLogistic",
                version = c(1,0,0),
                options = options,
                results = eduLogisticResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Guided Binomial Logistic Regression
#'
#' Model a binary outcome using numeric or categorical predictors with odds 
#' ratios, model-fit explanation, and reporting guidance.
#' 
#' @section References:
#' jReport
#'
#' parameters
#'
#' performance
#'
#' effectsize
#'
#' @param data .
#' @param outcome .
#' @param covariates .
#' @param factors .
#' @param ciWidth .
#' @param reportStyle .
#' @param reportFormat .
#' @param reportTone .
#' @param reportDescriptives .
#' @param reportAssumptions .
#' @param reportStatistic .
#' @param reportDf .
#' @param reportP .
#' @param reportEffect .
#' @param reportCI .
#' @param reportInterpretation .
#' @param reportCautions .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$overview} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$fit} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$coefficients} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$diagnostics} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$report} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$interpretation} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$fit$asDF}
#'
#' \code{as.data.frame(results$fit)}
#'
#' @export
eduLogistic <- function(
    data,
    outcome,
    covariates = NULL,
    factors = NULL,
    ciWidth = 95,
    reportStyle = "apa7",
    reportFormat = "paragraph",
    reportTone = "student_friendly",
    reportDescriptives = TRUE,
    reportAssumptions = TRUE,
    reportStatistic = TRUE,
    reportDf = TRUE,
    reportP = TRUE,
    reportEffect = TRUE,
    reportCI = TRUE,
    reportInterpretation = TRUE,
    reportCautions = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("eduLogistic requires jmvcore to be installed (restart may be required)")

    if ( ! missing(outcome)) outcome <- jmvcore::resolveQuo(jmvcore::enquo(outcome))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(outcome), outcome, NULL),
            `if`( ! missing(covariates), covariates, NULL),
            `if`( ! missing(factors), factors, NULL))

    for (v in outcome) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- eduLogisticOptions$new(
        outcome = outcome,
        covariates = covariates,
        factors = factors,
        ciWidth = ciWidth,
        reportStyle = reportStyle,
        reportFormat = reportFormat,
        reportTone = reportTone,
        reportDescriptives = reportDescriptives,
        reportAssumptions = reportAssumptions,
        reportStatistic = reportStatistic,
        reportDf = reportDf,
        reportP = reportP,
        reportEffect = reportEffect,
        reportCI = reportCI,
        reportInterpretation = reportInterpretation,
        reportCautions = reportCautions)

    analysis <- eduLogisticClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

