
# This file is automatically generated, you probably don't want to edit this

eduRMAnovaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "eduRMAnovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            measures = NULL,
            occasionLabels = "",
            ciWidth = 95,
            showPlot = TRUE,
            reportStyle = "apa7",
            reportFormat = "paragraph",
            reportTone = "student_friendly",
            reportDescriptives = TRUE,
            reportAssumptions = TRUE,
            reportStatistic = TRUE,
            reportDf = TRUE,
            reportP = TRUE,
            reportEffect = TRUE,
            reportCI = TRUE,
            reportInterpretation = TRUE,
            reportCautions = TRUE, ...) {

            super$initialize(
                package="jReport",
                name="eduRMAnova",
                requiresData=TRUE,
                ...)

            private$..measures <- jmvcore::OptionVariables$new(
                "measures",
                measures,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..occasionLabels <- jmvcore::OptionString$new(
                "occasionLabels",
                occasionLabels,
                default="")
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..showPlot <- jmvcore::OptionBool$new(
                "showPlot",
                showPlot,
                default=TRUE)
            private$..reportStyle <- jmvcore::OptionList$new(
                "reportStyle",
                reportStyle,
                options=list(
                    "apa7",
                    "plain",
                    "journal",
                    "dissertation"),
                default="apa7")
            private$..reportFormat <- jmvcore::OptionList$new(
                "reportFormat",
                reportFormat,
                options=list(
                    "short",
                    "paragraph",
                    "bullets",
                    "table_paragraph",
                    "copy_ready"),
                default="paragraph")
            private$..reportTone <- jmvcore::OptionList$new(
                "reportTone",
                reportTone,
                options=list(
                    "concise",
                    "student_friendly",
                    "detailed",
                    "critical"),
                default="student_friendly")
            private$..reportDescriptives <- jmvcore::OptionBool$new(
                "reportDescriptives",
                reportDescriptives,
                default=TRUE)
            private$..reportAssumptions <- jmvcore::OptionBool$new(
                "reportAssumptions",
                reportAssumptions,
                default=TRUE)
            private$..reportStatistic <- jmvcore::OptionBool$new(
                "reportStatistic",
                reportStatistic,
                default=TRUE)
            private$..reportDf <- jmvcore::OptionBool$new(
                "reportDf",
                reportDf,
                default=TRUE)
            private$..reportP <- jmvcore::OptionBool$new(
                "reportP",
                reportP,
                default=TRUE)
            private$..reportEffect <- jmvcore::OptionBool$new(
                "reportEffect",
                reportEffect,
                default=TRUE)
            private$..reportCI <- jmvcore::OptionBool$new(
                "reportCI",
                reportCI,
                default=TRUE)
            private$..reportInterpretation <- jmvcore::OptionBool$new(
                "reportInterpretation",
                reportInterpretation,
                default=TRUE)
            private$..reportCautions <- jmvcore::OptionBool$new(
                "reportCautions",
                reportCautions,
                default=TRUE)

            self$.addOption(private$..measures)
            self$.addOption(private$..occasionLabels)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..showPlot)
            self$.addOption(private$..reportStyle)
            self$.addOption(private$..reportFormat)
            self$.addOption(private$..reportTone)
            self$.addOption(private$..reportDescriptives)
            self$.addOption(private$..reportAssumptions)
            self$.addOption(private$..reportStatistic)
            self$.addOption(private$..reportDf)
            self$.addOption(private$..reportP)
            self$.addOption(private$..reportEffect)
            self$.addOption(private$..reportCI)
            self$.addOption(private$..reportInterpretation)
            self$.addOption(private$..reportCautions)
        }),
    active = list(
        measures = function() private$..measures$value,
        occasionLabels = function() private$..occasionLabels$value,
        ciWidth = function() private$..ciWidth$value,
        showPlot = function() private$..showPlot$value,
        reportStyle = function() private$..reportStyle$value,
        reportFormat = function() private$..reportFormat$value,
        reportTone = function() private$..reportTone$value,
        reportDescriptives = function() private$..reportDescriptives$value,
        reportAssumptions = function() private$..reportAssumptions$value,
        reportStatistic = function() private$..reportStatistic$value,
        reportDf = function() private$..reportDf$value,
        reportP = function() private$..reportP$value,
        reportEffect = function() private$..reportEffect$value,
        reportCI = function() private$..reportCI$value,
        reportInterpretation = function() private$..reportInterpretation$value,
        reportCautions = function() private$..reportCautions$value),
    private = list(
        ..measures = NA,
        ..occasionLabels = NA,
        ..ciWidth = NA,
        ..showPlot = NA,
        ..reportStyle = NA,
        ..reportFormat = NA,
        ..reportTone = NA,
        ..reportDescriptives = NA,
        ..reportAssumptions = NA,
        ..reportStatistic = NA,
        ..reportDf = NA,
        ..reportP = NA,
        ..reportEffect = NA,
        ..reportCI = NA,
        ..reportInterpretation = NA,
        ..reportCautions = NA)
)

eduRMAnovaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "eduRMAnovaResults",
    inherit = jmvcore::Group,
    active = list(
        overview = function() private$.items[["overview"]],
        main = function() private$.items[["main"]],
        descriptives = function() private$.items[["descriptives"]],
        diagnostics = function() private$.items[["diagnostics"]],
        report = function() private$.items[["report"]],
        interpretation = function() private$.items[["interpretation"]],
        plot = function() private$.items[["plot"]],
        methodsReferences = function() private$.items[["methodsReferences"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Guided Repeated-Measures ANOVA",
                refs=list(
                    "jReport",
                    "afex",
                    "effectsize",
                    "ggplot2",
                    "Cohen1988",
                    "Cumming2014"))
            self$add(jmvcore::Html$new(
                options=options,
                name="overview",
                title="jReport: Overview and Why This Test?"))
            self$add(jmvcore::Table$new(
                options=options,
                name="main",
                title="Within-Subjects Result and Effect Size",
                clearWith=list(
                    "measures",
                    "occasionLabels",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="term", 
                        `title`="Effect", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="F", 
                        `type`="number"),
                    list(
                        `name`="df1", 
                        `title`="df1", 
                        `type`="number"),
                    list(
                        `name`="df2", 
                        `title`="df2", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="effect", 
                        `title`="Partial Eta-squared", 
                        `type`="number"),
                    list(
                        `name`="ci_low", 
                        `title`="CI Lower", 
                        `type`="number"),
                    list(
                        `name`="ci_high", 
                        `title`="CI Upper", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="descriptives",
                title="Occasion Descriptives",
                clearWith=list(
                    "measures",
                    "occasionLabels",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="label", 
                        `title`="Occasion", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="diagnostics",
                title="Assumption Checks and Guidance",
                clearWith=list(
                    "measures",
                    "occasionLabels",
                    "ciWidth"),
                columns=list(
                    list(
                        `name`="check", 
                        `title`="Check", 
                        `type`="text"),
                    list(
                        `name`="tested", 
                        `title`="Tested?", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="status", 
                        `title`="Status", 
                        `type`="text"),
                    list(
                        `name`="interpretation", 
                        `title`="Interpretation", 
                        `type`="text",
                        `visible`=FALSE),
                    list(
                        `name`="action", 
                        `title`="Recommended Action", 
                        `type`="text",
                        `visible`=FALSE))))
            self$add(jmvcore::Html$new(
                options=options,
                name="report",
                title="Reporting"))
            self$add(jmvcore::Html$new(
                options=options,
                name="interpretation",
                title="Plain-Language Interpretation"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Visualisation",
                visible="(showPlot)",
                clearWith=list(
                    "measures",
                    "occasionLabels",
                    "ciWidth"),
                width=520,
                height=360,
                renderFun=".plot"))
            self$add(jmvcore::Html$new(
                options=options,
                name="methodsReferences",
                title="Methods and References"))}))

eduRMAnovaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "eduRMAnovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReport",
                name = "eduRMAnova",
                version = c(1,0,0),
                options = options,
                results = eduRMAnovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Guided Repeated-Measures ANOVA
#'
#' Compare repeated measurements from the same participants and explain 
#' sphericity and Greenhouse-Geisser-corrected inference.
#' 
#' @section References:
#' jReport
#'
#' afex
#'
#' effectsize
#'
#' ggplot2
#'
#' @param data .
#' @param measures .
#' @param occasionLabels .
#' @param ciWidth .
#' @param showPlot .
#' @param reportStyle .
#' @param reportFormat .
#' @param reportTone .
#' @param reportDescriptives .
#' @param reportAssumptions .
#' @param reportStatistic .
#' @param reportDf .
#' @param reportP .
#' @param reportEffect .
#' @param reportCI .
#' @param reportInterpretation .
#' @param reportCautions .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$overview} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$main} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$descriptives} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$diagnostics} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$report} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$interpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$methodsReferences} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$main$asDF}
#'
#' \code{as.data.frame(results$main)}
#'
#' @export
eduRMAnova <- function(
    data,
    measures,
    occasionLabels = "",
    ciWidth = 95,
    showPlot = TRUE,
    reportStyle = "apa7",
    reportFormat = "paragraph",
    reportTone = "student_friendly",
    reportDescriptives = TRUE,
    reportAssumptions = TRUE,
    reportStatistic = TRUE,
    reportDf = TRUE,
    reportP = TRUE,
    reportEffect = TRUE,
    reportCI = TRUE,
    reportInterpretation = TRUE,
    reportCautions = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("eduRMAnova requires jmvcore to be installed (restart may be required)")

    if ( ! missing(measures)) measures <- jmvcore::resolveQuo(jmvcore::enquo(measures))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(measures), measures, NULL))


    options <- eduRMAnovaOptions$new(
        measures = measures,
        occasionLabels = occasionLabels,
        ciWidth = ciWidth,
        showPlot = showPlot,
        reportStyle = reportStyle,
        reportFormat = reportFormat,
        reportTone = reportTone,
        reportDescriptives = reportDescriptives,
        reportAssumptions = reportAssumptions,
        reportStatistic = reportStatistic,
        reportDf = reportDf,
        reportP = reportP,
        reportEffect = reportEffect,
        reportCI = reportCI,
        reportInterpretation = reportInterpretation,
        reportCautions = reportCautions)

    analysis <- eduRMAnovaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

