
# This file is automatically generated, you probably don't want to edit this

eduReliabilityOmegaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "eduReliabilityOmegaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            items = NULL,
            reverseItems = list(),
            correlationType = "pearson",
            bootstrapCI = TRUE,
            bootstrapSamples = 200,
            ciWidth = 95,
            showPlot = TRUE,
            reportStyle = "apa7",
            reportFormat = "paragraph",
            reportTone = "student_friendly",
            reportDescriptives = TRUE,
            reportAssumptions = TRUE,
            reportEffect = TRUE,
            reportCI = TRUE,
            reportInterpretation = TRUE,
            reportCautions = TRUE, ...) {

            super$initialize(
                package="jReport",
                name="eduReliabilityOmega",
                requiresData=TRUE,
                ...)

            private$..items <- jmvcore::OptionVariables$new(
                "items",
                items,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..reverseItems <- jmvcore::OptionVariables$new(
                "reverseItems",
                reverseItems,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"),
                default=list())
            private$..correlationType <- jmvcore::OptionList$new(
                "correlationType",
                correlationType,
                options=list(
                    "pearson",
                    "polychoric"),
                default="pearson")
            private$..bootstrapCI <- jmvcore::OptionBool$new(
                "bootstrapCI",
                bootstrapCI,
                default=TRUE)
            private$..bootstrapSamples <- jmvcore::OptionNumber$new(
                "bootstrapSamples",
                bootstrapSamples,
                min=20,
                max=5000,
                default=200)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..showPlot <- jmvcore::OptionBool$new(
                "showPlot",
                showPlot,
                default=TRUE)
            private$..reportStyle <- jmvcore::OptionList$new(
                "reportStyle",
                reportStyle,
                options=list(
                    "apa7",
                    "plain",
                    "journal",
                    "dissertation"),
                default="apa7")
            private$..reportFormat <- jmvcore::OptionList$new(
                "reportFormat",
                reportFormat,
                options=list(
                    "short",
                    "paragraph",
                    "bullets",
                    "table_paragraph",
                    "copy_ready"),
                default="paragraph")
            private$..reportTone <- jmvcore::OptionList$new(
                "reportTone",
                reportTone,
                options=list(
                    "concise",
                    "student_friendly",
                    "detailed",
                    "critical"),
                default="student_friendly")
            private$..reportDescriptives <- jmvcore::OptionBool$new(
                "reportDescriptives",
                reportDescriptives,
                default=TRUE)
            private$..reportAssumptions <- jmvcore::OptionBool$new(
                "reportAssumptions",
                reportAssumptions,
                default=TRUE)
            private$..reportEffect <- jmvcore::OptionBool$new(
                "reportEffect",
                reportEffect,
                default=TRUE)
            private$..reportCI <- jmvcore::OptionBool$new(
                "reportCI",
                reportCI,
                default=TRUE)
            private$..reportInterpretation <- jmvcore::OptionBool$new(
                "reportInterpretation",
                reportInterpretation,
                default=TRUE)
            private$..reportCautions <- jmvcore::OptionBool$new(
                "reportCautions",
                reportCautions,
                default=TRUE)

            self$.addOption(private$..items)
            self$.addOption(private$..reverseItems)
            self$.addOption(private$..correlationType)
            self$.addOption(private$..bootstrapCI)
            self$.addOption(private$..bootstrapSamples)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..showPlot)
            self$.addOption(private$..reportStyle)
            self$.addOption(private$..reportFormat)
            self$.addOption(private$..reportTone)
            self$.addOption(private$..reportDescriptives)
            self$.addOption(private$..reportAssumptions)
            self$.addOption(private$..reportEffect)
            self$.addOption(private$..reportCI)
            self$.addOption(private$..reportInterpretation)
            self$.addOption(private$..reportCautions)
        }),
    active = list(
        items = function() private$..items$value,
        reverseItems = function() private$..reverseItems$value,
        correlationType = function() private$..correlationType$value,
        bootstrapCI = function() private$..bootstrapCI$value,
        bootstrapSamples = function() private$..bootstrapSamples$value,
        ciWidth = function() private$..ciWidth$value,
        showPlot = function() private$..showPlot$value,
        reportStyle = function() private$..reportStyle$value,
        reportFormat = function() private$..reportFormat$value,
        reportTone = function() private$..reportTone$value,
        reportDescriptives = function() private$..reportDescriptives$value,
        reportAssumptions = function() private$..reportAssumptions$value,
        reportEffect = function() private$..reportEffect$value,
        reportCI = function() private$..reportCI$value,
        reportInterpretation = function() private$..reportInterpretation$value,
        reportCautions = function() private$..reportCautions$value),
    private = list(
        ..items = NA,
        ..reverseItems = NA,
        ..correlationType = NA,
        ..bootstrapCI = NA,
        ..bootstrapSamples = NA,
        ..ciWidth = NA,
        ..showPlot = NA,
        ..reportStyle = NA,
        ..reportFormat = NA,
        ..reportTone = NA,
        ..reportDescriptives = NA,
        ..reportAssumptions = NA,
        ..reportEffect = NA,
        ..reportCI = NA,
        ..reportInterpretation = NA,
        ..reportCautions = NA)
)

eduReliabilityOmegaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "eduReliabilityOmegaResults",
    inherit = jmvcore::Group,
    active = list(
        overview = function() private$.items[["overview"]],
        main = function() private$.items[["main"]],
        items = function() private$.items[["items"]],
        diagnostics = function() private$.items[["diagnostics"]],
        report = function() private$.items[["report"]],
        interpretation = function() private$.items[["interpretation"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Guided Reliability: McDonald's Omega")
            self$add(jmvcore::Html$new(
                options=options,
                name="overview",
                title="jReport: Overview and Why Omega?"))
            self$add(jmvcore::Table$new(
                options=options,
                name="main",
                title="Reliability Estimate",
                columns=list(
                    list(
                        `name`="coefficient",
                        `title`="Coefficient",
                        `type`="text"),
                    list(
                        `name`="estimate",
                        `title`="Estimate",
                        `type`="number"),
                    list(
                        `name`="ci_low",
                        `title`="CI Lower",
                        `type`="number"),
                    list(
                        `name`="ci_high",
                        `title`="CI Upper",
                        `type`="number"),
                    list(
                        `name`="n",
                        `title`="Complete N",
                        `type`="integer"),
                    list(
                        `name`="items",
                        `title`="Items",
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="items",
                title="Item Quality Guidance",
                columns=list(
                    list(
                        `name`="item",
                        `title`="Item",
                        `type`="text"),
                    list(
                        `name`="scoring",
                        `title`="Scoring Direction",
                        `type`="text"),
                    list(
                        `name`="n",
                        `title`="N",
                        `type`="integer"),
                    list(
                        `name`="mean",
                        `title`="Mean",
                        `type`="number"),
                    list(
                        `name`="sd",
                        `title`="SD",
                        `type`="number"),
                    list(
                        `name`="item_total_r",
                        `title`="Corrected Item-Total r",
                        `type`="number"),
                    list(
                        `name`="loading",
                        `title`="Factor Loading",
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="diagnostics",
                title="Data and Interpretation Guidance",
                columns=list(
                    list(
                        `name`="check",
                        `title`="Check",
                        `type`="text"),
                    list(
                        `name`="tested",
                        `title`="Tested?",
                        `type`="text"),
                    list(
                        `name`="statistic",
                        `title`="Statistic",
                        `type`="number"),
                    list(
                        `name`="p",
                        `title`="p",
                        `type`="number",
                        `format`="zto,pvalue"),
                    list(
                        `name`="status",
                        `title`="Status",
                        `type`="text"),
                    list(
                        `name`="interpretation",
                        `title`="Interpretation",
                        `type`="text"),
                    list(
                        `name`="action",
                        `title`="Recommended Action",
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="report",
                title="Reporting"))
            self$add(jmvcore::Html$new(
                options=options,
                name="interpretation",
                title="Plain-Language Interpretation"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Item Contribution Plot",
                visible="(showPlot)",
                width=520,
                height=360,
                renderFun=".plot"))}))

eduReliabilityOmegaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "eduReliabilityOmegaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReport",
                name = "eduReliabilityOmega",
                version = c(0,1,0),
                options = options,
                results = eduReliabilityOmegaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Guided Reliability: McDonald's Omega
#'
#' Estimate and report internal consistency using McDonald's omega total, with
#' item diagnostics and clear interpretation guidance.
#'
#' @param data .
#' @param items .
#' @param reverseItems .
#' @param correlationType .
#' @param bootstrapCI .
#' @param bootstrapSamples .
#' @param ciWidth .
#' @param showPlot .
#' @param reportStyle .
#' @param reportFormat .
#' @param reportTone .
#' @param reportDescriptives .
#' @param reportAssumptions .
#' @param reportEffect .
#' @param reportCI .
#' @param reportInterpretation .
#' @param reportCautions .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$overview} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$main} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$items} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$diagnostics} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$report} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$interpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$main$asDF}
#'
#' \code{as.data.frame(results$main)}
#'
#' @export
eduReliabilityOmega <- function(
    data,
    items,
    reverseItems = list(),
    correlationType = "pearson",
    bootstrapCI = TRUE,
    bootstrapSamples = 200,
    ciWidth = 95,
    showPlot = TRUE,
    reportStyle = "apa7",
    reportFormat = "paragraph",
    reportTone = "student_friendly",
    reportDescriptives = TRUE,
    reportAssumptions = TRUE,
    reportEffect = TRUE,
    reportCI = TRUE,
    reportInterpretation = TRUE,
    reportCautions = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("eduReliabilityOmega requires jmvcore to be installed (restart may be required)")

    if ( ! missing(items)) items <- jmvcore::resolveQuo(jmvcore::enquo(items))
    if ( ! missing(reverseItems)) reverseItems <- jmvcore::resolveQuo(jmvcore::enquo(reverseItems))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(items), items, NULL),
            `if`( ! missing(reverseItems), reverseItems, NULL))


    options <- eduReliabilityOmegaOptions$new(
        items = items,
        reverseItems = reverseItems,
        correlationType = correlationType,
        bootstrapCI = bootstrapCI,
        bootstrapSamples = bootstrapSamples,
        ciWidth = ciWidth,
        showPlot = showPlot,
        reportStyle = reportStyle,
        reportFormat = reportFormat,
        reportTone = reportTone,
        reportDescriptives = reportDescriptives,
        reportAssumptions = reportAssumptions,
        reportEffect = reportEffect,
        reportCI = reportCI,
        reportInterpretation = reportInterpretation,
        reportCautions = reportCautions)

    analysis <- eduReliabilityOmegaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

