
# This file is automatically generated, you probably don't want to edit this

jrReportCorrMatrixOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportCorrMatrixOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="JamoviReport",
                name="jrReportCorrMatrix",
                requiresData=TRUE,
                ...)


        }),
    active = list(),
    private = list()
)

jrReportCorrMatrixResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportCorrMatrixResults",
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Automatic Report for Correlation Matrix")}))

jrReportCorrMatrixBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportCorrMatrixBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "JamoviReport",
                name = "jrReportCorrMatrix",
                version = c(0,1,0),
                options = options,
                results = jrReportCorrMatrixResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Automatic Report for Correlation Matrix
#'
#' 
#' @param data .
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
jrReportCorrMatrix <- function(
    data) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jrReportCorrMatrix requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- jrReportCorrMatrixOptions$new()

    analysis <- jrReportCorrMatrixClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

