
# This file is automatically generated, you probably don't want to edit this

jrReportLinRegOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportLinRegOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="jReport",
                name="jrReportLinReg",
                requiresData=TRUE,
                ...)


        }),
    active = list(),
    private = list()
)

jrReportLinRegResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportLinRegResults",
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Automatic Report for Linear Regression")}))

jrReportLinRegBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportLinRegBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReport",
                name = "jrReportLinReg",
                version = c(1,0,0),
                options = options,
                results = jrReportLinRegResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Automatic Report for Linear Regression
#'
#' 
#' @section References:
#' jmvcore
#'
#' parameters
#'
#' performance
#'
#' effectsize
#'
#' @param data .
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
jrReportLinReg <- function(
    data) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jrReportLinReg requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- jrReportLinRegOptions$new()

    analysis <- jrReportLinRegClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

