
# This file is automatically generated, you probably don't want to edit this

jrReportAnovaOneWOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportAnovaOneWOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="JamoviReport",
                name="jrReportAnovaOneW",
                requiresData=TRUE,
                ...)


        }),
    active = list(),
    private = list()
)

jrReportAnovaOneWResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportAnovaOneWResults",
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Automatic Report for One-Way ANOVA")}))

jrReportAnovaOneWBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportAnovaOneWBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "JamoviReport",
                name = "jrReportAnovaOneW",
                version = c(0,1,0),
                options = options,
                results = jrReportAnovaOneWResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Automatic Report for One-Way ANOVA
#'
#' 
#' @param data .
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
jrReportAnovaOneW <- function(
    data) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jrReportAnovaOneW requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- jrReportAnovaOneWOptions$new()

    analysis <- jrReportAnovaOneWClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

