
# This file is automatically generated, you probably don't want to edit this

jrReportTTestISOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportTTestISOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="jReport",
                name="jrReportTTestIS",
                requiresData=TRUE,
                ...)


        }),
    active = list(),
    private = list()
)

jrReportTTestISResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportTTestISResults",
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Automatic Report for Independent Samples T-Test")}))

jrReportTTestISBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportTTestISBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReport",
                name = "jrReportTTestIS",
                version = c(0,1,0),
                options = options,
                results = jrReportTTestISResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Automatic Report for Independent Samples T-Test
#'
#'
#' @param data .
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
jrReportTTestIS <- function(
    data) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jrReportTTestIS requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- jrReportTTestISOptions$new()

    analysis <- jrReportTTestISClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

