
# This file is automatically generated, you probably don't want to edit this

jrReportPropTestNOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportPropTestNOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {
            super$initialize(
                package="jReport",
                name="jrReportPropTestN",
                requiresData=TRUE,
                ...)
        }),
    active = list(),
    private = list()
)

jrReportPropTestNResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportPropTestNResults",
    inherit = jmvcore::Group,
    active = list(
        jReportApaTable = function() private$.items[["jReportApaTable"]],
        jReportAssumptions = function() private$.items[["jReportAssumptions"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Automatic Report for Proportion Test")
            self$add(jmvcore::Table$new(
                options=options,
                name="jReportApaTable",
                title="APA Results Summary (jReport)",
                refs=list(
                    "jReport",
                    "jmvcore",
                    "effectsize"),
                columns=list(
                    list(`name`="analysis",`title`="Analysis",`type`="text"),
                    list(`name`="test",`title`="Test / Effect",`type`="text"),
                    list(`name`="statistic",`title`="Statistic",`type`="number"),
                    list(`name`="df1",`title`="df1",`type`="number"),
                    list(`name`="df2",`title`="df2",`type`="text"),
                    list(`name`="p",`title`="p",`type`="number",`format`="zto,pvalue"),
                    list(`name`="effect",`title`="Effect Size",`type`="text"),
                    list(`name`="ci",`title`="Effect 95% CI",`type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="jReportAssumptions",
                title="Assumptions and Recommended Actions (jReport)",
                refs=list(
                    "jReport",
                    "jmvcore",
                    "effectsize"),
                columns=list(
                    list(`name`="analysis",`title`="Analysis",`type`="text"),
                    list(`name`="assumption",`title`="Assumption / Check",`type`="text"),
                    list(`name`="tested",`title`="Tested?",`type`="text"),
                    list(`name`="statistic",`title`="Statistic",`type`="number"),
                    list(`name`="p",`title`="p",`type`="number",`format`="zto,pvalue"),
                    list(`name`="met",`title`="Met?",`type`="text"),
                    list(`name`="interpretation",`title`="What This Means",`type`="text"),
                    list(`name`="action",`title`="Recommended Action",`type`="text"))))}))

jrReportPropTestNBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportPropTestNBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReport",
                name = "jrReportPropTestN",
                version = c(1,0,0),
                options = options,
                results = jrReportPropTestNResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = "auto")
        }))

#' Automatic Report for Proportion Test
#'
#'
#' @section References:
#' jReport
#'
#' jmvcore
#'
#' effectsize
#'
#' @param data .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$jReportApaTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$jReportAssumptions} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' @export
jrReportPropTestN <- function(data) {
    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jrReportPropTestN requires jmvcore to be installed (restart may be required)")
    if (missing(data))
        data <- jmvcore::marshalData(parent.frame())
    options <- jrReportPropTestNOptions$new()
    analysis <- jrReportPropTestNClass$new(options = options, data = data)
    analysis$run()
    analysis$results
}

