
# This file is automatically generated, you probably don't want to edit this

jrReportMancovaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportMancovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="jReport",
                name="jrReportMancova",
                requiresData=TRUE,
                ...)


        }),
    active = list(),
    private = list()
)

jrReportMancovaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportMancovaResults",
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Automatic Report for MANOVA / MANCOVA")}))

jrReportMancovaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportMancovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReport",
                name = "jrReportMancova",
                version = c(1,0,0),
                options = options,
                results = jrReportMancovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Automatic Report for MANOVA / MANCOVA
#'
#' 
#' @section References:
#' jmvcore
#'
#' car
#'
#' effectsize
#'
#' @param data .
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
jrReportMancova <- function(
    data) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jrReportMancova requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- jrReportMancovaOptions$new()

    analysis <- jrReportMancovaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

