
# This file is automatically generated, you probably don't want to edit this

jrReportContTablesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportContTablesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {
            super$initialize(
                package="jReport",
                name="jrReportContTables",
                requiresData=TRUE,
                ...)
        }),
    active = list(),
    private = list()
)

jrReportContTablesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportContTablesResults",
    inherit = jmvcore::Group,
    active = list(
        jReportApaTable = function() private$.items[["jReportApaTable"]],
        jReportAssumptions = function() private$.items[["jReportAssumptions"]],
        jReportCells = function() private$.items[["jReportCells"]],
        jReportHeading = function() private$.items[["jReportHeading"]],
        jReportCard = function() private$.items[["jReportCard"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Automatic Report for Contingency Tables")
            self$add(jmvcore::Html$new(
                options=options,
                name="jReportHeading",
                title="jReport: Automatic Reporting",
                refs=list(                    "jReport",
                    "jmvcore",
                    "effectsize")))
            self$add(jmvcore::Table$new(
                options=options,
                name="jReportApaTable",
                title="APA Results Summary (jReport)",
                refs=list(                    "jReport",
                    "jmvcore",
                    "effectsize"),
                columns=list(                    list(`name`="analysis",`title`="Analysis",`type`="text"),
                    list(`name`="test",`title`="Test / Effect",`type`="text"),
                    list(`name`="statistic",`title`="Statistic",`type`="number"),
                    list(`name`="df1",`title`="df1",`type`="number"),
                    list(`name`="df2",`title`="df2",`type`="text"),
                    list(`name`="p",`title`="p",`type`="number",`format`="zto,pvalue"),
                    list(`name`="effect",`title`="Effect Size",`type`="text"),
                    list(`name`="ci",`title`="Effect 95% CI",`type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="jReportAssumptions",
                title="Assumptions and Recommended Actions (jReport)",
                refs=list(                    "jReport",
                    "jmvcore",
                    "effectsize"),
                columns=list(                    list(`name`="analysis",`title`="Analysis",`type`="text"),
                    list(`name`="assumption",`title`="Assumption / Check",`type`="text"),
                    list(`name`="tested",`title`="Tested?",`type`="text"),
                    list(`name`="statistic",`title`="Statistic",`type`="number"),
                    list(`name`="p",`title`="p",`type`="number",`format`="zto,pvalue"),
                    list(`name`="met",`title`="Met?",`type`="text"),
                    list(`name`="interpretation",`title`="What This Means",`type`="text"),
                    list(`name`="action",`title`="Recommended Action",`type`="text"))))
            self$add(jmvcore::Table$new(
                options=options, name="jReportCells",
                title="Observed and Expected Counts (jReport)", visible=FALSE,
                refs=list(                    "jReport",
                    "jmvcore",
                    "effectsize"),
                columns=list(                    list(`name`="analysis",`title`="Analysis",`type`="text"),
                    list(`name`="category",`title`="Cell / Category",`type`="text"),
                    list(`name`="observed",`title`="Observed",`type`="number"),
                    list(`name`="expected",`title`="Expected",`type`="number"),
                    list(`name`="standardised_residual",`title`="Standardised Residual",`type`="number"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="jReportCard",
                title="Automatic Report (jReport)",
                refs=list(                    "jReport",
                    "jmvcore",
                    "effectsize")))}))

jrReportContTablesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportContTablesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReport",
                name = "jrReportContTables",
                version = c(1,0,0),
                options = options,
                results = jrReportContTablesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = "auto")
        }))

#' Automatic Report for Contingency Tables
#'
#' @section References:
#' jReport
#'
#' jmvcore
#'
#' effectsize
#'
#' @param data .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$jReportApaTable} \tab \tab \tab \tab \tab a result item \cr
#'   \code{results$jReportAssumptions} \tab \tab \tab \tab \tab a result item \cr
#'   \code{results$jReportCells} \tab \tab \tab \tab \tab a result item \cr
#'   \code{results$jReportHeading} \tab \tab \tab \tab \tab a result item \cr
#'   \code{results$jReportCard} \tab \tab \tab \tab \tab a result item \cr
#' }
#'
#' @export
jrReportContTables <- function(data) {
    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jrReportContTables requires jmvcore to be installed (restart may be required)")
    if (missing(data))
        data <- jmvcore::marshalData(parent.frame())
    options <- jrReportContTablesOptions$new()
    analysis <- jrReportContTablesClass$new(options = options, data = data)
    analysis$run()
    analysis$results
}

