
# This file is automatically generated, you probably don't want to edit this

jrReportLogRegMultiOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportLogRegMultiOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {
            super$initialize(
                package="jReport",
                name="jrReportLogRegMulti",
                requiresData=TRUE,
                ...)
        }),
    active = list(),
    private = list()
)

jrReportLogRegMultiResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportLogRegMultiResults",
    inherit = jmvcore::Group,
    active = list(
        jReportApaTable = function() private$.items[["jReportApaTable"]],
        jReportAssumptions = function() private$.items[["jReportAssumptions"]],
        jReportCoefficients = function() private$.items[["jReportCoefficients"]],
        jReportHeading = function() private$.items[["jReportHeading"]],
        jReportCard = function() private$.items[["jReportCard"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Automatic Report for Multinomial Logistic Regression")
            self$add(jmvcore::Html$new(
                options=options,
                name="jReportHeading",
                title="jReport: Automatic Reporting",
                refs=list(                    "jReport",
                    "jmvcore",
                    "parameters",
                    "performance",
                    "effectsize")))
            self$add(jmvcore::Table$new(
                options=options,
                name="jReportApaTable",
                title="APA Results Summary (jReport)",
                refs=list(                    "jReport",
                    "jmvcore",
                    "parameters",
                    "performance",
                    "effectsize"),
                columns=list(                    list(`name`="analysis",`title`="Analysis",`type`="text"),
                    list(`name`="test",`title`="Test / Effect",`type`="text"),
                    list(`name`="statistic",`title`="Statistic",`type`="number"),
                    list(`name`="df1",`title`="df1",`type`="number"),
                    list(`name`="df2",`title`="df2",`type`="text"),
                    list(`name`="p",`title`="p",`type`="number",`format`="zto,pvalue"),
                    list(`name`="effect",`title`="Effect Size",`type`="text"),
                    list(`name`="ci",`title`="Effect 95% CI",`type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="jReportAssumptions",
                title="Assumptions and Recommended Actions (jReport)",
                refs=list(                    "jReport",
                    "jmvcore",
                    "parameters",
                    "performance",
                    "effectsize"),
                columns=list(                    list(`name`="analysis",`title`="Analysis",`type`="text"),
                    list(`name`="assumption",`title`="Assumption / Check",`type`="text"),
                    list(`name`="tested",`title`="Tested?",`type`="text"),
                    list(`name`="statistic",`title`="Statistic",`type`="number"),
                    list(`name`="p",`title`="p",`type`="number",`format`="zto,pvalue"),
                    list(`name`="met",`title`="Met?",`type`="text"),
                    list(`name`="interpretation",`title`="What This Means",`type`="text"),
                    list(`name`="action",`title`="Recommended Action",`type`="text"))))
            self$add(jmvcore::Table$new(
                options=options, name="jReportCoefficients",
                title="Relative Risk Ratios and Coefficients (jReport)", visible=FALSE,
                refs=list(                    "jReport",
                    "jmvcore",
                    "parameters",
                    "performance",
                    "effectsize"),
                columns=list(                    list(`name`="predictor",`title`="Predictor",`type`="text"),
                    list(`name`="estimate",`title`="B",`type`="number"),
                    list(`name`="se",`title`="SE",`type`="number"),
                    list(`name`="statistic",`title`="z",`type`="number"),
                    list(`name`="p",`title`="p",`type`="number",`format`="zto,pvalue"),
                    list(`name`="odds_ratio",`title`="Odds Ratio",`type`="number"),
                    list(`name`="confidence_interval",`title`="Odds Ratio 95% CI",`type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="jReportCard",
                title="Automatic Report (jReport)",
                refs=list(                    "jReport",
                    "jmvcore",
                    "parameters",
                    "performance",
                    "effectsize")))}))

jrReportLogRegMultiBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportLogRegMultiBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReport",
                name = "jrReportLogRegMulti",
                version = c(1,0,0),
                options = options,
                results = jrReportLogRegMultiResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = "auto")
        }))

#' Automatic Report for Multinomial Logistic Regression
#'
#' @section References:
#' jReport
#'
#' jmvcore
#'
#' parameters
#'
#' performance
#'
#' effectsize
#'
#' @param data .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$jReportApaTable} \tab \tab \tab \tab \tab a result item \cr
#'   \code{results$jReportAssumptions} \tab \tab \tab \tab \tab a result item \cr
#'   \code{results$jReportCoefficients} \tab \tab \tab \tab \tab a result item \cr
#'   \code{results$jReportHeading} \tab \tab \tab \tab \tab a result item \cr
#'   \code{results$jReportCard} \tab \tab \tab \tab \tab a result item \cr
#' }
#'
#' @export
jrReportLogRegMulti <- function(data) {
    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jrReportLogRegMulti requires jmvcore to be installed (restart may be required)")
    if (missing(data))
        data <- jmvcore::marshalData(parent.frame())
    options <- jrReportLogRegMultiOptions$new()
    analysis <- jrReportLogRegMultiClass$new(options = options, data = data)
    analysis$run()
    analysis$results
}

