
# This file is automatically generated, you probably don't want to edit this

jrReportContTablesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportContTablesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="JamoviReport",
                name="jrReportContTables",
                requiresData=TRUE,
                ...)


        }),
    active = list(),
    private = list()
)

jrReportContTablesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportContTablesResults",
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Automatic Report for Chi-Square Independence")}))

jrReportContTablesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportContTablesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "JamoviReport",
                name = "jrReportContTables",
                version = c(0,1,0),
                options = options,
                results = jrReportContTablesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Automatic Report for Chi-Square Independence
#'
#'
#' @param data .
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
jrReportContTables <- function(
    data) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jrReportContTables requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- jrReportContTablesOptions$new()

    analysis <- jrReportContTablesClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

