
# This file is automatically generated, you probably don't want to edit this

jrReportLogRegBinOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportLogRegBinOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="jReport",
                name="jrReportLogRegBin",
                requiresData=TRUE,
                ...)


        }),
    active = list(),
    private = list()
)

jrReportLogRegBinResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportLogRegBinResults",
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Automatic Report for Binomial Logistic Regression")}))

jrReportLogRegBinBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportLogRegBinBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReport",
                name = "jrReportLogRegBin",
                version = c(0,1,0),
                options = options,
                results = jrReportLogRegBinResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Automatic Report for Binomial Logistic Regression
#'
#'
#' @param data .
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
jrReportLogRegBin <- function(
    data) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jrReportLogRegBin requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- jrReportLogRegBinOptions$new()

    analysis <- jrReportLogRegBinClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

