
# This file is automatically generated, you probably don't want to edit this

jrReportAnovaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportAnovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="jReport",
                name="jrReportAnova",
                requiresData=TRUE,
                ...)


        }),
    active = list(),
    private = list()
)

jrReportAnovaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportAnovaResults",
    inherit = jmvcore::Group,
    active = list(
        jReportHeading = function() private$.items[["jReportHeading"]],
        jReportApaTable = function() private$.items[["jReportApaTable"]],
        jReportAssumptions = function() private$.items[["jReportAssumptions"]],
        jReportPostHoc = function() private$.items[["jReportPostHoc"]],
        jReportCard = function() private$.items[["jReportCard"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Automatic Report for ANOVA",
                refs=list(
                    "Cohen1988",
                    "Cumming2014"))
            self$add(jmvcore::Html$new(
                options=options,
                name="jReportHeading",
                title="jReport: Automatic Reporting"))
            self$add(jmvcore::Table$new(
                options=options,
                name="jReportApaTable",
                title="APA Results Summary (jReport)",
                refs=list(
                    "RCore",
                    "jReport",
                    "jmvcore",
                    "afex",
                    "effectsize",
                    "emmeans",
                    "Cohen1988",
                    "Cumming2014"),
                columns=list(
                    list(
                        `name`="analysis", 
                        `title`="Analysis", 
                        `type`="text"),
                    list(
                        `name`="test", 
                        `title`="Test / Effect", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="df1", 
                        `title`="df1", 
                        `type`="number"),
                    list(
                        `name`="df2", 
                        `title`="df2", 
                        `type`="text"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="effect", 
                        `title`="Effect Size", 
                        `type`="text"),
                    list(
                        `name`="ci", 
                        `title`="Effect 95% CI", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="jReportAssumptions",
                title="Assumptions and Recommended Actions (jReport)",
                refs=list(
                    "RCore",
                    "jReport",
                    "jmvcore",
                    "afex",
                    "effectsize",
                    "emmeans",
                    "Cohen1988",
                    "Cumming2014"),
                columns=list(
                    list(
                        `name`="analysis", 
                        `title`="Analysis", 
                        `type`="text"),
                    list(
                        `name`="assumption", 
                        `title`="Assumption / Check", 
                        `type`="text"),
                    list(
                        `name`="tested", 
                        `title`="Tested?", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="met", 
                        `title`="Met?", 
                        `type`="text"),
                    list(
                        `name`="interpretation", 
                        `title`="What This Means", 
                        `type`="text"),
                    list(
                        `name`="action", 
                        `title`="Recommended Action", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="jReportPostHoc",
                title="APA Post Hoc Comparisons (jReport)",
                visible="no",
                refs=list(
                    "RCore",
                    "jReport",
                    "jmvcore",
                    "afex",
                    "effectsize",
                    "emmeans",
                    "Cohen1988",
                    "Cumming2014"),
                columns=list(
                    list(
                        `name`="analysis", 
                        `title`="Analysis", 
                        `type`="text"),
                    list(
                        `name`="term", 
                        `title`="Factor / Term", 
                        `type`="text"),
                    list(
                        `name`="comparison", 
                        `title`="Comparison", 
                        `type`="text"),
                    list(
                        `name`="mean_difference", 
                        `title`="Mean Difference", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="number"),
                    list(
                        `name`="statistic", 
                        `title`="t", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="Adjusted p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="adjustment", 
                        `title`="Adjustment", 
                        `type`="text"),
                    list(
                        `name`="significant", 
                        `title`="Significant?", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="jReportCard",
                title="Automatic Report (jReport)"))}))

jrReportAnovaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportAnovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReport",
                name = "jrReportAnova",
                version = c(1,0,0),
                options = options,
                results = jrReportAnovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Automatic Report for ANOVA
#'
#' 
#' @section References:
#' RCore
#'
#' jReport
#'
#' jmvcore
#'
#' afex
#'
#' effectsize
#'
#' emmeans
#'
#' @param data .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$jReportHeading} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$jReportApaTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$jReportAssumptions} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$jReportPostHoc} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$jReportCard} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$jReportApaTable$asDF}
#'
#' \code{as.data.frame(results$jReportApaTable)}
#'
#' @export
jrReportAnova <- function(
    data) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jrReportAnova requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- jrReportAnovaOptions$new()

    analysis <- jrReportAnovaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

