
# This file is automatically generated, you probably don't want to edit this

jrReportTTestPSOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportTTestPSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="jReport",
                name="jrReportTTestPS",
                requiresData=TRUE,
                ...)


        }),
    active = list(),
    private = list()
)

jrReportTTestPSResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportTTestPSResults",
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Automatic Report for Paired Samples T-Test")}))

jrReportTTestPSBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportTTestPSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReport",
                name = "jrReportTTestPS",
                version = c(1,0,0),
                options = options,
                results = jrReportTTestPSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Automatic Report for Paired Samples T-Test
#'
#' 
#' @section References:
#' jReport
#'
#' jmvcore
#'
#' effectsize
#'
#' BayesFactor
#'
#' @param data .
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
jrReportTTestPS <- function(
    data) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jrReportTTestPS requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- jrReportTTestPSOptions$new()

    analysis <- jrReportTTestPSClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

