
# This file is automatically generated, you probably don't want to edit this

jrReportTTestPSOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportTTestPSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            pAdjustment = "holm", ...) {

            super$initialize(
                package="jReport",
                name="jrReportTTestPS",
                requiresData=TRUE,
                ...)

            private$..pAdjustment <- jmvcore::OptionList$new(
                "pAdjustment",
                pAdjustment,
                options=list(
                    "holm",
                    "bonferroni",
                    "none"),
                default="holm")

            self$.addOption(private$..pAdjustment)
        }),
    active = list(
        pAdjustment = function() private$..pAdjustment$value),
    private = list(
        ..pAdjustment = NA)
)

jrReportTTestPSResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportTTestPSResults",
    inherit = jmvcore::Group,
    active = list(
        jReportHeading = function() private$.items[["jReportHeading"]],
        jReportApaTable = function() private$.items[["jReportApaTable"]],
        jReportAssumptions = function() private$.items[["jReportAssumptions"]],
        jReportCard = function() private$.items[["jReportCard"]],
        jReportInterpretation = function() private$.items[["jReportInterpretation"]],
        methodsReferences = function() private$.items[["methodsReferences"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Automatic Report for Paired Samples T-Test")
            self$add(jmvcore::Html$new(
                options=options,
                name="jReportHeading",
                title="jReport: Automatic Reporting"))
            self$add(jmvcore::Table$new(
                options=options,
                name="jReportApaTable",
                title="APA Results Summary (jReport)",
                columns=list(
                    list(
                        `name`="analysis", 
                        `title`="Analysis", 
                        `type`="text"),
                    list(
                        `name`="test", 
                        `title`="Test / Effect", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="df1", 
                        `title`="df1", 
                        `type`="number"),
                    list(
                        `name`="df2", 
                        `title`="df2", 
                        `type`="text"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number",
                        `format`="zto,pvalue"),
                    list(
                        `name`="p_adjusted",
                        `title`="Adjusted p",
                        `type`="number",
                        `format`="zto,pvalue",
                        `visible`=FALSE),
                    list(
                        `name`="adjustment_result",
                        `title`="Result after adjustment",
                        `type`="text",
                        `visible`=FALSE),
                    list(
                        `name`="effect", 
                        `title`="Effect Size", 
                        `type`="text",
                        `visible`=FALSE),
                    list(
                        `name`="ci", 
                        `title`="Effect 95% CI", 
                        `type`="text",
                        `visible`=FALSE))))
            self$add(jmvcore::Table$new(
                options=options,
                name="jReportAssumptions",
                title="Assumptions and Recommended Actions (jReport)",
                columns=list(
                    list(
                        `name`="analysis", 
                        `title`="Analysis", 
                        `type`="text"),
                    list(
                        `name`="assumption", 
                        `title`="Assumption / Check", 
                        `type`="text"),
                    list(
                        `name`="tested", 
                        `title`="Tested?", 
                        `type`="text"),
                    list(
                        `name`="statistic", 
                        `title`="Statistic", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number",
                        `format`="zto,pvalue"),
                    list(
                        `name`="met", 
                        `title`="Met?", 
                        `type`="text"),
                    list(
                        `name`="interpretation", 
                        `title`="What This Means", 
                        `type`="text",
                        `visible`=FALSE),
                    list(
                        `name`="action", 
                        `title`="Recommended Action", 
                        `type`="text",
                        `visible`=FALSE))))
            self$add(jmvcore::Html$new(
                options=options,
                name="jReportCard",
                title="Automatic Report (jReport)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="jReportInterpretation",
                title="Interpretation Guidance (jReport)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="methodsReferences",
                title="Methods and References"))}))

jrReportTTestPSBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportTTestPSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReport",
                name = "jrReportTTestPS",
                version = c(1,0,0),
                options = options,
                results = jrReportTTestPSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Automatic Report for Paired Samples T-Test
#'
#' 
#' @section References:
#' RCore
#'
#' jReport
#'
#' jmvcore
#'
#' effectsize
#'
#' BayesFactor
#'
#' @param data .
#' @param pAdjustment When several related t-tests address the same overall
#'   research question, adjustment controls the increased familywise Type I
#'   error risk. Holm is recommended for most confirmatory analyses and is
#'   generally less conservative than Bonferroni.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$jReportHeading} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$jReportApaTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$jReportAssumptions} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$jReportCard} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$jReportInterpretation} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$methodsReferences} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$jReportApaTable$asDF}
#'
#' \code{as.data.frame(results$jReportApaTable)}
#'
#' @export
jrReportTTestPS <- function(
    data,
    pAdjustment = "holm") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jrReportTTestPS requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- jrReportTTestPSOptions$new(
        pAdjustment = pAdjustment)

    analysis <- jrReportTTestPSClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
