
# This file is automatically generated, you probably don't want to edit this

jrReportReliabilityOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportReliabilityOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="jReport",
                name="jrReportReliability",
                requiresData=TRUE,
                ...)


        }),
    active = list(),
    private = list()
)

jrReportReliabilityResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportReliabilityResults",
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Automatic Omega Report for Reliability Analysis")}))

jrReportReliabilityBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportReliabilityBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReport",
                name = "jrReportReliability",
                version = c(1,0,0),
                options = options,
                results = jrReportReliabilityResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Automatic Omega Report for Reliability Analysis
#'
#' 
#' @section References:
#' jmvcore
#'
#' psych
#'
#' @param data .
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
jrReportReliability <- function(
    data) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jrReportReliability requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- jrReportReliabilityOptions$new()

    analysis <- jrReportReliabilityClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

