
# This file is automatically generated, you probably don't want to edit this

jrReportPropTestNOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportPropTestNOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="jReport",
                name="jrReportPropTestN",
                requiresData=TRUE,
                ...)


        }),
    active = list(),
    private = list()
)

jrReportPropTestNResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportPropTestNResults",
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Automatic Report for Chi-Square Goodness-of-Fit")}))

jrReportPropTestNBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportPropTestNBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jReport",
                name = "jrReportPropTestN",
                version = c(0,1,0),
                options = options,
                results = jrReportPropTestNResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Automatic Report for Chi-Square Goodness-of-Fit
#'
#'
#' @param data .
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
jrReportPropTestN <- function(
    data) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jrReportPropTestN requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- jrReportPropTestNOptions$new()

    analysis <- jrReportPropTestNClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

