
# This file is automatically generated, you probably don't want to edit this

jrReportAncovaOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportAncovaOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="JamoviReport",
                name="jrReportAncova",
                requiresData=TRUE,
                ...)


        }),
    active = list(),
    private = list()
)

jrReportAncovaResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportAncovaResults",
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Automatic Report for ANCOVA")}))

jrReportAncovaBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jrReportAncovaBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "JamoviReport",
                name = "jrReportAncova",
                version = c(0,1,0),
                options = options,
                results = jrReportAncovaResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Automatic Report for ANCOVA
#'
#' 
#' @param data .
#' @return A results object containing:
#' \tabular{llllll}{
#' }
#'
#' @export
jrReportAncova <- function(
    data) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jrReportAncova requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- jrReportAncovaOptions$new()

    analysis <- jrReportAncovaClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

